# Generated by Django 4.2.7 on 2024-05-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmdb_mgmt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instancepermission",
            name="permission_type",
            field=models.CharField(
                choices=[("query", "查询"), ("manage", "管理")],
                db_index=True,
                default="query",
                max_length=100,
                verbose_name="权限类型",
            ),
        ),
    ]
