# Generated by Django 4.2.7 on 2024-05-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmdb_mgmt", "0002_instancepermission_permission_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInstancePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_by",
                    models.CharField(default="", max_length=32, verbose_name="创建者"),
                ),
                (
                    "updated_by",
                    models.CharField(default="", max_length=32, verbose_name="更新者"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=100, verbose_name="用户名"),
                ),
                (
                    "model_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="模型ID"
                    ),
                ),
                (
                    "permission_type",
                    models.CharField(
                        choices=[("query", "查询"), ("manage", "管理")],
                        db_index=True,
                        default="query",
                        max_length=100,
                        verbose_name="权限类型",
                    ),
                ),
                ("conditions", models.JSONField(default=list, verbose_name="条件列表")),
            ],
            options={
                "verbose_name": "时间相关字段",
                "abstract": False,
            },
        ),
    ]
