# Generated by Django 4.2.7 on 2024-05-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmdb_mgmt", "0004_showfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="instancepermission",
            name="resource_type",
            field=models.CharField(
                choices=[("fixed", "指定资产"), ("changing", "条件资产")],
                default="changing",
                max_length=100,
                verbose_name="资产类型",
            ),
        ),
        migrations.AddField(
            model_name="userinstancepermission",
            name="resource_type",
            field=models.CharField(
                choices=[("fixed", "指定资产"), ("changing", "条件资产")],
                default="changing",
                max_length=100,
                verbose_name="资产类型",
            ),
        ),
    ]
