# Generated by Django 4.2.7 on 2024-06-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmdb_mgmt", "0006_rolecredentialpermission_usercredentialpermission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolecredentialpermission",
            name="inst_id",
            field=models.IntegerField(db_index=True, verbose_name="凭据实例ID"),
        ),
        migrations.AlterField(
            model_name="usercredentialpermission",
            name="inst_id",
            field=models.IntegerField(db_index=True, verbose_name="凭据实例ID"),
        ),
    ]
