# Generated by Django 4.2.7 on 2024-06-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cmdb_mgmt", "0008_alter_rolecredentialpermission_inst_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changerecord",
            name="label",
            field=models.CharField(max_length=50, verbose_name="标签ID"),
        ),
    ]
