# Generated by Django 4.2.7 on 2024-01-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuManage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "created_by",
                    models.CharField(default="", max_length=32, verbose_name="创建者"),
                ),
                (
                    "updated_by",
                    models.CharField(default="", max_length=32, verbose_name="更新者"),
                ),
                (
                    "menu_name",
                    models.CharField(help_text="菜单名称", max_length=64, unique=True),
                ),
                ("default", models.BooleanField(default=False, help_text="是否是内置菜单")),
                ("use", models.BooleanField(default=False, help_text="是否启用(只能有一个)")),
                ("menu", models.JSONField(help_text="菜单内容")),
            ],
            options={
                "verbose_name": "菜单管理",
            },
        ),
        migrations.CreateModel(
            name="OperationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operator",
                    models.CharField(db_index=True, max_length=128, null=True),
                ),
                (
                    "operate_type",
                    models.CharField(
                        choices=[
                            ("add", "新增"),
                            ("modify", "修改"),
                            ("exec", "执行"),
                            ("delete", "删除"),
                            ("download", "下载"),
                            ("upload", "上传"),
                            ("login", "登陆"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="添加时间"
                    ),
                ),
                (
                    "operate_obj",
                    models.CharField(db_index=True, default="", max_length=200),
                ),
                ("operate_summary", models.TextField(default="")),
                (
                    "app_module",
                    models.CharField(db_index=True, default="", max_length=20),
                ),
                (
                    "obj_type",
                    models.CharField(db_index=True, default="", max_length=30),
                ),
            ],
            options={
                "verbose_name": "使用记录",
            },
        ),
        migrations.CreateModel(
            name="SysSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                (
                    "created_by",
                    models.CharField(default="", max_length=32, verbose_name="创建者"),
                ),
                (
                    "updated_by",
                    models.CharField(default="", max_length=32, verbose_name="更新者"),
                ),
                (
                    "vtype",
                    models.CharField(
                        default="string", max_length=32, verbose_name="类型"
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="设置项"),
                ),
                ("value", models.TextField(verbose_name="设置值")),
                (
                    "desc",
                    models.CharField(default="", max_length=200, verbose_name="设置描述"),
                ),
            ],
            options={
                "verbose_name": "系统设置",
            },
        ),
    ]
