# Generated by Django 4.2.7 on 2024-05-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "system_mgmt",
            "0002_alter_menumanage_options_alter_operationlog_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GradedRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(max_length=100, unique=True, verbose_name="角色名"),
                ),
                (
                    "superior_role",
                    models.CharField(
                        db_index=True,
                        default="admin",
                        max_length=100,
                        verbose_name="上级角色",
                    ),
                ),
            ],
            options={
                "verbose_name": "分级角色表",
                "verbose_name_plural": "分级角色表",
            },
        ),
    ]
