# Generated by Django 4.2.7 on 2024-07-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_mgmt", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="sidecar_sync_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="sidecar同步时间"
            ),
        ),
    ]
