# Generated by Django 4.2.7 on 2024-07-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("node_mgmt", "0002_alter_node_sidecar_sync_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="os_type",
            field=models.CharField(default="", max_length=100, verbose_name="操作系统类型"),
        ),
    ]
